<!-- Our Services Section -->
<div id="our-services" class="our-services section py-4">
  <h3 class="section-title text-center my-5">Apresentação</h3>
  <div class="features py-4 mb-4">
    <div class="container">
      <div class="row">
        <div class="feature py-4 col-md-12 d-flex">
          <div class="icon mr-3"><i class="fa fa-bullhorn"></i></div>
          <div class="px-12 text-justify h6">
              <p>
                O SITe (Seminário de Informática e Tecnologia) é um evento tradicional que acontece anualmente no
                Centro de Ciências Tecnológicas (CCT) da Universidade Estadual do Norte do Paraná (UENP),
                em Bandeirantes (Campus Luiz Meneghel).
                O evento é destinado à comunidade universitária, profissionais das áreas de tecnologia
                da informação (TI), educação e ciências sociais. Neste ano de 2019, teremos a 12ª
                edição do evento e acontecerá de 21 a 24 de agosto de 2019.
              </p>
              <p class="text-right">
                <a class="btn btn-sm btn-squared btn-secondary" href="nav.php?page=apresentacao">Leia Mais...</a>
              </p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="feature py-4 col-md-6 d-flex">
          <div class="icon text-primary mr-3"><i class="fas fa-user-astronaut"></i></div>
          <div class="px-4">
              <h5>Inscrições</h5>
              <p>As inscrições para o evento e também para os minicursos devem ser realizadas a partir de XX de XXXXX de 2019.
                <br/><br/><a href="nav.php?page=inscricao" class="btn btn-sm btn-primary btn-squared">Inscrições (Em breve)</a></p>
          </div>
        </div>
        <div class="feature py-4 col-md-6 d-flex">
          <div class="icon text-danger mr-3"><i class="far fa-calendar-check"></i></div>
          <div class="px-4">
              <h5>Programação</h5>
              <p>O evento ocorrerá entre os dias 21 e 24 de agosto de 2019 com palestras e minicursos relacionados a TIC.
              <br/><br/><a href="nav.php?page=programacao" class="btn btn-sm btn-danger btn-squared">Ver programação completa</a></p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="feature py-4 col-md-6 d-flex">
          <div class="icon text-success mr-3"><i class="far fa-paper-plane"></i></div>
          <div class="px-4">
              <h5>Submissão de Trabalhos</h5>
              <p>A chamada de trabalhos será em formato de resumo expandido. Os artigos aceitos serão apresentados no evento.
                <br/><br/><a href="nav.php?page=submissao" class="btn btn-sm btn-success btn-squared">Saiba Mais</a></p>
          </div>
        </div>
        <div class="feature py-4 col-md-6 d-flex">
          <div class="icon text-info mr-3"><i class="fas fa-laptop-code"></i></div>
          <div class="px-4">
              <h5>Minicursos</h5>
              <p>Os minicursos são eventos de curta duração que apresentam uma visão
                geral de um tópico relacionado à área de TIC.
              <br/><br/><a href="nav.php?page=minicursos" class="btn btn-sm btn-info btn-squared">Confira a lista de minicursos</a></p>
          </div>
        </div>
      </div>


    </div>
  </div>
  <!-- / Features -->
</div>
<!-- / Our Services Section -->
