<!-- Faleconosco Section -->
<div class="testimonials section-invert py-4">
    <h3 class="section-title text-center m-5">Fale Conosco</h3>
    <div class="container py-5">
      <div class="row">
          <div class="col">
            <p class="text-center h5">Em caso de dúvidas entre em contato conosco utilizando um dos canais abaixo </p>
            <div class="spacer-50"> </div>
            <div class="h6 text-center">
              <p> <i class="fab fa-whatsapp text-success"></i> Whatsapp: +55 43 9 9968-4031 (Prof. Biluka)</p>
              <p> <i class="far fa-envelope text-danger"></i> <a href="mailto:cct@uenp.edu.br">cct@uenp.edu.br</a> - Centro de Ciências Tecnológicas</p>
              <p> <i class="fab fa-facebook text-primary"></i> <a href="https://www.facebook.com/siuenp">Página do CCT no Facebook</a></p>
            </div>
          </div>
      </div>
    </div>
</div>
