<!-- Faleconosco Section -->
<div class="testimonials section-invert py-4">
    <h3 class="section-title text-center m-5">Fale Conosco</h3>
    <div class="container py-5">
      <div class="row">
          <div class="col">
            <p class="text-center h4">Em caso de dúvidas entre em contato conosco utilizando um dos canais abaixo </p>
            <div class="spacer"> </div>
            <div class="h5 text-center">
              <p> <i class="fab fa-whatsapp text-success"></i> Whatsapp: +55 (43) 9 9999-1234 (Prof. Biluka)</p>
              <p> <i class="far fa-envelope text-danger"></i> E-mail:  <cct@uenp.edu.br> Centro de Ciências Tecnológicas</p>
              <p> <i class="fab fa-facebook text-primary"></i> Facebook: <a href="https://facebook.com/siteuenp">https://facebook.com/siteuenp</a></p>
            </div>
          </div>
      </div>
    </div>
</div>
