<footer>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="#"> <?=$data['name']?></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Início <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Incrições</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Submissões</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Programação</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Fale Conosco</a>
          </li>
        </ul>
      </div>

    </div>
  </nav>
</footer>
