

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class="carousel-caption d-none d-md-block">
        <h5 class="text-white">Caption Title</h5>
        <p>Caption Subtitle</p>
      </div>
    </div>
    <div class="carousel-item">
      <div class="carousel-caption d-none d-md-block">
        <h5 class="text-white">Caption Title</h5>
        <p>Caption Subtitle</p>
      </div>
    </div>
    <div class="carousel-item">
      <div class="carousel-caption d-none d-md-block">
        <h5 class="text-white">Caption Title</h5>
        <p>Caption Subtitle</p>
      </div>
    </div>
    <div class="carousel-item">
      <div class="carousel-caption d-none d-md-block">
        <h5 class="text-white">Caption Title</h5>
        <p>Caption Subtitle</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


    <!-- Our Blog Section -->
    <div class="blog section section py-4">
      <h3 class="section-title text-center m-5">Minicursos</h3>

      <div class="container">
        <div class="py-4">
          <div class="row">
            <div class="card-deck">
            <div class="col-md-12 col-lg-4">
              <div class="card mb-4">
                <img class="card-img-top" src="images/common/card-1.jpg" alt="Card image cap">
                <div class="card-body">
                  <h4 class="card-title">Find Great Places to Work While Travelling</h4>
                  <p class="card-text">He seems sinking under the evidence could not only grieve and a visit. The father is to bless and placed in his length hid...</p>
                  <a class="btn btn-primary btn-pill" href="#">Read More &rarr;</a>
                </div>
              </div>
            </div>

            <div class="col-md-12 col-lg-4">
              <div class="card mb-4">
                <img class="card-img-top" src="images/common/card-3.jpg" alt="Card image cap">
                <div class="card-body">
                  <h4 class="card-title">Quick Tips for Improving Your Website's Design</h4>
                  <p class="card-text">He seems sinking under the evidence could not only grieve and a visit. The father is to bless and placed in his length hid...</p>
                  <a class="btn btn-primary btn-pill" href="#">Read More &rarr;</a>
                </div>
              </div>
            </div>

            <div class="col-md-12 col-lg-4">
              <div class="card mb-4">
                <img class="card-img-top" src="images/common/card-2.jpg" alt="Card image cap">
                <div class="card-body">
                  <h4 class="card-title">A Designer's Tips While Travelling and Working</h4>
                  <p class="card-text">He seems sinking under the evidence could not only grieve and a visit. The father is to bless and placed in his length hid...</p>
                  <a class="btn btn-primary btn-pill" href="#">Read More &rarr;</a>
                </div>
              </div>
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- / Our Blog Section -->
