    <!-- Our Blog Section -->
<div class="blog section section py-4">
  <h3 class="section-title text-center m-5">Minicursos</h3>
  <div class="container">
    <div class="py-4">
      <div class="row">
        <div class="card-deck">
          <div class="col-md-12 col-lg-4">
            <div class="card mb-4">
              <img class="card-img-top" src="images/common/docker.png" alt="Docker">
              <div class="card-body">
                <h4 class="card-title text-center">Docker: Administrando Containers</h4>
                <p class="card-text text-justify">Este curso abordará a famosa tecnologia de containers, já adotada por grandes
                  empresas como Paypal, Visa, Spotify, Netflix, entre outras...
                </p>
                <p class="text-right"><a class="btn btn-outline-primary btn-sm btn-pill" href="nav.php?page=detalhe-minicurso">Leia mais &rarr;</a></p>
              </div>
            </div>
          </div>

          <div class="col-md-12 col-lg-4">
            <div class="card mb-4">
              <img class="card-img-top" src="images/common/docker-plus-maven.jpg" alt="DockerMaven">
              <div class="card-body">
                <h4 class="card-title text-center">Simplificando testes de integração com Docker e Maven</h4>
                <p class="card-text text-justify">Neste minicurso eu procuro apresentar como testes de integração
                  podem ser mais simples usando o Docker, criando um ecossistema de aplicações...
                </p>
                <p class="text-right"><a class="btn btn-outline-primary btn-sm btn-pill" href="nav.php?page=detalhe-minicurso">Leia mais &rarr;</a></p>
              </div>
            </div>
          </div>

          <div class="col-md-12 col-lg-4">
            <div class="card py-4">
              <div class="card-body">
                <h4 class="card-title text-center">Em breve teremos mais novidades...</h4>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
    <!-- / Our Blog Section -->
