<div class="container">
<nav class="navbar navbar-expand-lg navbar-dark pt-4 px-0">
  <a class="navbar-brand" href="#">
    <?=$data['name']?>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Início</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Incrições</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Submissões</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Programação</a>
      </li>
    </ul>

    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="https://twitter.com/cct"><i class="fab fa-twitter"></i></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://www.facebook.com/cct"><i class="fab fa-facebook"></i></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://cct.uenp.edu.br"><i class="fas fa-globe"></i></a>
      </li>
    </ul>
  </div>
</nav>
</div>
