<!-- Testimonials Section -->
<div class="testimonials section-invert py-4">
    <h3 class="section-title text-center m-5">Palestrantes Confirmados</h3>
    <div class="container py-5">
      <div class="row">
          <div class="col-md-4 testimonial text-center">
              <div class="avatar rounded-circle with-shadows mb-3 ml-auto mr-auto">
                  <img src="images/common/avatar-1.jpeg" class="w-100" alt="Testimonial Avatar" />
              </div>
              <h5 class="mb-1">Osbourne Tranter</h5>
              <span class="text-muted d-block mb-2">CEO at Megacorp</span>
              <p>Vivamus quis ex mattis, gravida erat a, iaculis urna. Proin ac eleifend tortor. Nunc in augue eget enim venenatis viverra.</p>
              <div class="btn-group" role="group" aria-label="Basic example">
                <button type="button" class="btn btn-danger">A</button>
                <button type="button" class="btn btn-danger">B</button>
                <button type="button" class="btn btn-danger">C</button>
              </div>
          </div>

          <div class="col-md-4 testimonial text-center">
              <div class="avatar rounded-circle with-shadows mb-3 ml-auto mr-auto">
                  <img src="images/common/avatar-2.jpeg" class="w-100" alt="Testimonial Avatar" />
              </div>
              <h5 class="mb-1">Darrin Ollie</h5>
              <span class="text-muted d-block mb-2">CEO at Megacorp</span>
              <p>Nullam eu ligula facilisis, commodo velit non, vulputate dolor. Aenean congue euismod vestibulum.</p>
          </div>

          <div class="col-md-4 testimonial text-center">
              <div class="avatar rounded-circle with-shadows mb-3 ml-auto mr-auto">
                  <img src="images/common/avatar-3.jpeg" class="w-100" alt="Testimonial Avatar" />
              </div>
              <h5 class="mb-1">Quinton Bruce</h5>
              <span class="text-muted d-block mb-2">CEO at Megacorp</span>
              <p> Aenean imperdiet ultrices tortor id convallis. Donec id metus magna. Morbi pretium odio faucibus blandit gravida.</p>
          </div>
      </div>
    </div>
</div>
