<!-- Testimonials Section -->
<div class="testimonials section-invert py-4">
    <h3 class="section-title text-center m-5">Profissionais Confirmados</h3>
    <div class="container py-5">
      <div class="row">
        <div class="col-md-4 testimonial text-center">
            <div class="avatar rounded-circle with-shadows mb-3 ml-auto mr-auto">
                <img src="images/avatar/elielson-barbosa.png" class="w-100" alt="Testimonial Avatar" />
            </div>
            <h5 class="mb-1">Elielson Barbosa de Souza</h5>
            <span class="text-muted d-block mb-2">
              Sistemas de Informação/2014
              <br/>
              Operações de Infraestrutura do TRT da 15o Região
            </span>
            <span class="text-center h5">
              <i class="fab fa-facebook text-primary"></i>
              <i class="fab fa-twitter text-info"></i>
              <i class="fas fa-envelope text-danger"></i>
            </span>
            <h4>Docker: Administrando Containers</h4>
        </div>
        <div class="col-md-4 testimonial text-center">
            <div class="avatar rounded-circle with-shadows mb-3 ml-auto mr-auto">
                <img src="images/avatar/erikson-aguiar.png" class="w-100" alt="Testimonial Avatar" />
            </div>
            <h5 class="mb-1">Erikson Júlio de Aguiar</h5>
            <span class="text-muted d-block mb-2">
              Ciência da Computação/2017
              <br/>
              Mestrando no ICMC/USP
            </span>
            <span class="text-center h5">
              <i class="fab fa-facebook text-primary"></i>
              <i class="fab fa-twitter text-info"></i>
              <i class="fas fa-envelope text-danger"></i>
            </span>
            <h4>Fundamentos e desafios do blockchain 3.0.</h4>
        </div>
        <div class="col-md-4 testimonial text-center">
            <div class="avatar rounded-circle with-shadows mb-3 ml-auto mr-auto">
                <img src="images/avatar/roberto-elero.png" class="w-100" alt="Testimonial Avatar" />
            </div>
            <h5 class="mb-1">Roberto Elero Junior</h5>
            <span class="text-muted d-block mb-2">
              Sistemas de Informação/2015
              <br/>
              Desenvolvedor Java no iFood
            </span>
            <span class="text-center h5">
              <i class="fab fa-facebook text-primary"></i>
              <i class="fab fa-twitter text-info"></i>
              <i class="fas fa-envelope text-danger"></i>
            </span>
            <h4>Migrando microsserviços legados com segurança</h4>
        </div>
      </div>
    </div>
</div>
