<div class="inner-wrapper mt-auto mb-auto container">

  <div class="row">
    <div class="col-md-9">
        <h1 class="welcome-heading display-3 text-white">
        <img src="images/logo_mini.png" class="img-main" alt="<?=$data['name']?>">
          <?=$data['name']?>
        </h1>
        <h2 class="welcome-heading display-5 text-white"><?=$data['fullname']?></h2>
        <p class="text-white h6 text-justify"><?=$data['description']?></p>
        <a href="#" class="btn btn-lg btn-primary btn-squared align-self-center main-button">Inscrições Abertas</a>

        <a href="#" class="btn btn-lg btn-secondary btn-squared align-self-center main-button">Submissão de Trabalhos</a>
    </div>
  </div>
</div>
<!-- / Inner Wrapper -->
